spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  application:
    name: employee-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/